# Generated by Django 5.2.7 on 2025-11-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='year_level',
            field=models.CharField(default='1st Year', max_length=20),
            preserve_default=False,
        ),
    ]
