# Generated by Django 5.0.2 on 2025-11-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_class_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='year_level',
            field=models.CharField(default='1st Year', max_length=20),
        ),
    ]
