# Generated by Django 5.2.7 on 2025-11-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_transmutationtable_gradecategory_gradeitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesummary',
            name='equivalent_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
