# Generated by Django 5.2.7 on 2025-11-23 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeitem',
            name='date_recorded',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 11, 23)),
            preserve_default=False,
        ),
    ]
